# Generated by Django 5.0.7 on 2025-06-10 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('competitor_number', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=100)),
                ('HD', models.CharField(blank=True, max_length=20)),
                ('Tof', models.CharField(blank=True, max_length=20)),
                ('D', models.CharField(blank=True, max_length=20)),
                ('P', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('judge_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JudgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='django_py.contester')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='django_py.judge')),
            ],
            options={
                'unique_together': {('contester', 'judge', 'round_number')},
            },
        ),
    ]
