# Generated by Django 5.0.7 on 2025-06-11 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_py', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contester',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judge',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='judge_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
