# Generated by Django 5.0.7 on 2025-10-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_py', '0003_alter_judge_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contester',
            options={'ordering': ['competitor_number'], 'verbose_name': 'Contester', 'verbose_name_plural': 'Contesters'},
        ),
        migrations.AlterModelOptions(
            name='judge',
            options={'ordering': ['judge_number'], 'verbose_name': 'Judge', 'verbose_name_plural': 'Judges'},
        ),
        migrations.AddField(
            model_name='judge',
            name='is_main_judge',
            field=models.BooleanField(default=False),
        ),
    ]
