# Generated by Django 5.0.7 on 2025-10-22 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_py', '0004_alter_contester_options_alter_judge_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='judge_type',
            field=models.CharField(choices=[('execution', 'Execution Judge'), ('difficulty', 'Difficulty Judge')], default='execution', help_text='Type of judge: execution (rounds) or difficulty (single score)', max_length=20),
        ),
        migrations.CreateModel(
            name='DifficultyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.DecimalField(decimal_places=3, help_text='Difficulty score from 0.000 to 50.000', max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_scores', to='django_py.contester')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_scores', to='django_py.judge')),
            ],
            options={
                'unique_together': {('contester', 'judge')},
            },
        ),
    ]
