# Generated by Django 5.0.7 on 2025-10-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_py', '0005_judge_judge_type_difficultyscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgerating',
            name='deduction',
            field=models.FloatField(default=0.0, help_text='Deduction in tenths (0.1, 0.2, etc.)'),
        ),
        migrations.AddField(
            model_name='judgerating',
            name='landing_score',
            field=models.FloatField(default=0.0, help_text='Landing score for this jump'),
        ),
    ]
