# Generated by Django 5.0.7 on 2025-11-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_py', '0006_judgerating_deduction_judgerating_landing_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contester',
            name='D',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contester',
            name='HD',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contester',
            name='P',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contester',
            name='Tof',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
